### PR TITLE
Add test if sets configured in rector file are applied

### PR DESCRIPTION
**Pull request by mzeis**
Adds a failing test case for https://github.com/rectorphp/rector/issues/3965 as suggested by @TomasVotruba in this [comment](https://github.com/rectorphp/rector/issues/3965#issuecomment-674822352).

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Could you rebase on `master`? It might be fixed now

**Comment by mzeis** [comment]
@TomasVotruba I did a rebase, the check is passing now.

**Review by TomasVotruba — COMMENTED** [review]
Could you move this file into `/tests`, so it's obvious it's related to testing?

**Comment by mzeis** [comment]
@TomasVotruba Done.

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
